Convert port to string because the error.
error: NoMethodError: undefined method `strip' for 3128:Fixnum
It occured on
/usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http/header.rb:17:in
`block in initialize_http_header'.